spring:
  application:
    name: api-gateway

server:
  port: 9020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/,http://localhost:9011/eureka/,http://localhost:9012/eureka/

zuul:
  routes:
    eureka-produce-hello: /phello/**
