spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Youngod/springcloud-config-repo.git
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/,http://localhost:9011/eureka/,http://localhost:9012/eureka/

